sudo: false
language: node_js
node_js:
- 7.4.0
cache:
  directories:
  - node_modules
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: xTC2IIx3r5rbIRGTUku4SboESUua7+jKpmMRNOZSSyNb5kN8HnQEWSy9hFL8EUxygh1JDLynIoQPRiJ3e1yqxS++I9i6Awt14fNlzzuYfneUl3EF4KgIMa9RPqB6ZR061dadeFX3kiLvjJ/fT6+dVShKB1p9deIlPxk7BXuamKCa+hlPBTzhrZbQ2rMLP/ucPlspIBGm/1KjJc3t/JM8k8W+kMl66thFS+MfttbpLTpwfaNosPjUQ3QOhwEPGJtPQIBnWqxx52+enx5ePZBVridnPW+LXdmLS8E5R59VKZkCvUM3SEdCuWWwr03+e+L2uSvMGf/Z4AKI8lmN/V5+WXgbit8X5jWSO6Kiqd76i30o1O1y3p7dYaqi5Lz2FaxdmDeap4uG1xhcRsJHUcFPHqnQJpNuD6e15C3ETK41fN7yRZ4dE2yiGXc8R5787W5RLh1+r43Mk6dfxsGd0cJ1c2OfcoluEaFgzafeb+d3Ff6YaW55x2dKCZeUydFxco+RDrrbdzvugss2D46aDGBAPfyw/KojvEPaMG7VtBZln4a+8J5SlRbMR2jjNupjsGp7NC8MLNMRFMWLOzi/LRUcIh7NVXmguZ6gbwWouVacRVV4jADaKZXfj5Qcd5rOtJydYxFdCDgiwI35/KhlLrQbCMpo4sHG1zYy6xrEroLqzmE=
